<?php

namespace App\Services;

use App\Models\Enrollment;
use App\Models\PromoCode;
use App\Models\PromoRedemption;
use App\Models\User;
use Illuminate\Validation\ValidationException;

/**
 * Percentage promo codes with a one-use-per-user rule.
 *
 * A redemption is created 'pending' alongside the enrollment and only marked
 * 'completed' when the payment lands. Abandoned attempts are DELETED (never
 * flagged) by the lazy cleanup so the user's single slot frees up again — the
 * UNIQUE(promo_code_id, user_id) index is what actually enforces the rule.
 */
class PromoCodeService
{
    /** Autogenerated codes avoid O/I/0/1 — they get read over the phone. */
    public const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

    public function normalize(string $code): string
    {
        return strtoupper(trim($code));
    }

    /**
     * Resolve and validate a code for this user, or throw a ValidationException
     * keyed on 'promo_code'. Creates nothing — redeem() does that.
     */
    public function validateForUser(string $code, User $user): PromoCode
    {
        $code = $this->normalize($code);

        $promo = PromoCode::where('code', $code)->first();

        if (! $promo || ! $promo->active) {
            throw ValidationException::withMessages(['promo_code' => 'This promo code is not valid.']);
        }

        if ($promo->isExpired()) {
            throw ValidationException::withMessages(['promo_code' => 'This promo code has expired.']);
        }

        $this->releaseAbandoned($promo);

        if ($promo->redemptions()->where('user_id', $user->id)->exists()) {
            throw ValidationException::withMessages(['promo_code' => 'You have already used this promo code.']);
        }

        if ($promo->max_uses !== null && $promo->redemptions()->count() >= $promo->max_uses) {
            throw ValidationException::withMessages(['promo_code' => 'This promo code has been fully redeemed.']);
        }

        return $promo;
    }

    /**
     * Claim the user's slot on this code. Call inside the same DB transaction
     * that saves the enrollment so a failed save releases the claim.
     */
    public function redeem(PromoCode $promo, User $user, Enrollment $enrollment): PromoRedemption
    {
        try {
            return PromoRedemption::create([
                'promo_code_id' => $promo->id,
                'user_id' => $user->id,
                'enrollment_id' => $enrollment->id,
                'status' => 'pending',
            ]);
        } catch (\Illuminate\Database\QueryException $e) {
            // Unique violation — a concurrent request won the slot.
            throw ValidationException::withMessages(['promo_code' => 'You have already used this promo code.']);
        }
    }

    /** Called when the enrollment's payment is confirmed (webhook or admin approval). */
    public function completeFor(Enrollment $enrollment): void
    {
        PromoRedemption::where('enrollment_id', $enrollment->id)
            ->where('status', 'pending')
            ->update(['status' => 'completed', 'completed_at' => now()]);
    }

    /** Random 8-char code from the unambiguous alphabet. */
    public function generateCode(int $length = 8): string
    {
        do {
            $code = '';
            for ($i = 0; $i < $length; $i++) {
                $code .= self::ALPHABET[random_int(0, strlen(self::ALPHABET) - 1)];
            }
        } while (PromoCode::where('code', $code)->exists());

        return $code;
    }

    /**
     * Lazy cleanup: drop pending redemptions older than 24h that clearly went
     * nowhere — no enrollment at all, or an unpaid enrollment with no manual
     * payment awaiting review (i.e. an abandoned gateway attempt).
     */
    private function releaseAbandoned(PromoCode $promo): void
    {
        PromoRedemption::where('promo_code_id', $promo->id)
            ->where('status', 'pending')
            ->where('created_at', '<', now()->subHours(24))
            ->where(function ($q) {
                $q->whereNull('enrollment_id')
                    ->orWhereHas('enrollment', function ($e) {
                        $e->where('payment_status', 'unpaid')->whereDoesntHave('manualPayments');
                    });
            })
            ->delete();
    }
}
